// <auto-generated />
using System;
using EstateFlow.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstateFlow.Server.Migrations
{
    [DbContext(typeof(EstateFlowDbContext))]
    [Migration("20260927193416_AddMeter")]
    partial class AddMeter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstateFlow.Server.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kecskemét"
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Meter");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f8fad5b-d9cb-469f-a165-70867728950e"),
                            Location = "Basement",
                            Name = "Electricity Meter",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            SerialNumber = "ELEC123456"
                        },
                        new
                        {
                            Id = new Guid("3c9e6679-7425-40de-944b-e07456789012"),
                            Location = "Utility Room",
                            Name = "Water Meter",
                            PropertyId = new Guid("7c9e6679-7425-40de-944b-e07456789012"),
                            SerialNumber = "WATR654321"
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdvertisementText")
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Address = "123 Main Street, Budapest",
                            AdvertisementText = "Experience luxury living in the heart of Budapest!",
                            CityId = 1,
                            Code = "BUD-001",
                            Name = "Luxury Apartment in Budapest",
                            SquareMeters = 54
                        },
                        new
                        {
                            Id = new Guid("7c9e6679-7425-40de-944b-e07456789012"),
                            Address = "456 Oak Avenue, Kecskemét",
                            AdvertisementText = "A perfect home for your family in Kecskemét!",
                            CityId = 8,
                            Code = "KEC-001",
                            Name = "Cozy Family Home in Kecskemét",
                            SquareMeters = 120
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            FilePath = "uploads/properties/budapest_apartment_hall0.jpg",
                            Name = "Hall",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            UploadedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2c9e6679-7425-40de-944b-e07456789012"),
                            FilePath = "uploads/properties/budapest_apartment_livingroom0.jpg",
                            Name = "Living Room",
                            PropertyId = new Guid("7c9e6679-7425-40de-944b-e07456789012"),
                            UploadedAt = new DateTime(2026, 2, 11, 10, 12, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Meter", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.PropertyImage", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
