// <auto-generated />
using System;
using EstateFlow.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstateFlow.Server.Migrations
{
    [DbContext(typeof(EstateFlowDbContext))]
    [Migration("20261001203759_AddDomainEntities")]
    partial class AddDomainEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstateFlow.Server.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kecskemét"
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("ReadingPeriod")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("UtilityTypeId");

                    b.ToTable("Meters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3301"),
                            Location = "Living Room",
                            Name = "Electricity Meter",
                            Note = "Need to be validated in 2007",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            ProviderId = 1,
                            ReadingPeriod = "Monthly",
                            SerialNumber = "ELEC-001",
                            UtilityTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3302"),
                            Location = "Kitchen",
                            Name = "Water Meter",
                            Note = "Need to be validated in 2007",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            ProviderId = 2,
                            ReadingPeriod = "Quarterly",
                            SerialNumber = "WATER-001",
                            UtilityTypeId = 2
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            Location = "Garage",
                            Name = "Gas Meter",
                            Note = "Need to be validated in 2007 ",
                            PropertyId = new Guid("7c9e6679-7425-40de-944b-e07456789012"),
                            ProviderId = 3,
                            SerialNumber = "GAS-001",
                            UtilityTypeId = 3
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("MesuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.ToTable("MeterReadings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            ApprovedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            MesuredAt = new DateTime(2026, 6, 1, 7, 40, 0, 0, DateTimeKind.Utc),
                            MeterId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3301"),
                            PhotoPath = "uploads/meter_readings/electricity_reading_2026-06-01.jpg",
                            ReportedAt = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Value = 120.5m
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3305"),
                            ApprovedAt = new DateTime(2026, 6, 1, 9, 5, 0, 0, DateTimeKind.Utc),
                            MesuredAt = new DateTime(2026, 6, 1, 7, 45, 0, 0, DateTimeKind.Utc),
                            MeterId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3302"),
                            PhotoPath = "uploads/meter_readings/water_reading_2026-06-01.jpg",
                            ReportedAt = new DateTime(2026, 6, 1, 8, 5, 0, 0, DateTimeKind.Utc),
                            Value = 85.2m
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3306"),
                            ApprovedAt = new DateTime(2026, 6, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            MesuredAt = new DateTime(2026, 6, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            MeterId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            PhotoPath = "uploads/meter_readings/gas_reading_2026-06-01.jpg",
                            ReportedAt = new DateTime(2026, 6, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            Value = 65.8m
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdvertisementText")
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Address = "123 Main Street, Budapest",
                            AdvertisementText = "Experience luxury living in the heart of Budapest!",
                            CityId = 1,
                            Code = "BUD-001",
                            Name = "Luxury Apartment in Budapest",
                            SquareMeters = 54
                        },
                        new
                        {
                            Id = new Guid("7c9e6679-7425-40de-944b-e07456789012"),
                            Address = "456 Oak Avenue, Kecskemét",
                            AdvertisementText = "A perfect home for your family in Kecskemét!",
                            CityId = 8,
                            Code = "KEC-001",
                            Name = "Cozy Family Home in Kecskemét",
                            SquareMeters = 120
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            FilePath = "uploads/properties/budapest_apartment_hall0.jpg",
                            Name = "Hall",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            UploadedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2c9e6679-7425-40de-944b-e07456789012"),
                            FilePath = "uploads/properties/budapest_apartment_livingroom0.jpg",
                            Name = "Living Room",
                            PropertyId = new Guid("7c9e6679-7425-40de-944b-e07456789012"),
                            UploadedAt = new DateTime(2026, 2, 11, 10, 12, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilityTypeId");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electricity Provider A",
                            UtilityTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Water Provider B",
                            UtilityTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gas Provider C",
                            UtilityTypeId = 3
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f2504e0-4f89-41d3-9a0c-0305e82c3309"),
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonthlyRent = 120000m,
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("5f2504e0-4f89-41d3-9a0c-0305e82c3307")
                        },
                        new
                        {
                            Id = new Guid("6f2504e0-4f89-41d3-9a0c-0305e82c3310"),
                            MonthlyRent = 150000m,
                            PropertyId = new Guid("7c9e6679-7425-40de-944b-e07456789012"),
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("5f2504e0-4f89-41d3-9a0c-0305e82c3308")
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f2504e0-4f89-41d3-9a0c-0305e82c3307"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = new Guid("5f2504e0-4f89-41d3-9a0c-0305e82c3308"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "+00 00 123 4567"
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.UtilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UtilityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electricity"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gas"
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Meter", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany("Meters")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstateFlow.Server.Domain.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstateFlow.Server.Domain.UtilityType", "UtilityType")
                        .WithMany()
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Provider");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.MeterReading", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Meter", "Meter")
                        .WithMany("MeterReadings")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.PropertyImage", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Provider", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.UtilityType", "UtilityType")
                        .WithMany("Providers")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Rental", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstateFlow.Server.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Meter", b =>
                {
                    b.Navigation("MeterReadings");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Meters");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.UtilityType", b =>
                {
                    b.Navigation("Providers");
                });
#pragma warning restore 612, 618
        }
    }
}
